name: CI - Build & Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up QEMU (multi-platform support)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push backend image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: ./backend/Dockerfile   # 👈 chỉ đúng file
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/faceblur-backend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/faceblur-backend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build & push frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          file: ./frontend/Dockerfile  # 👈 chỉ đúng file
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/faceblur-frontend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/faceblur-frontend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
